app = "agent-automation-frontend"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_ENV = "production"
  NEXT_PUBLIC_AI_PROVIDER_URL = "https://agent-automation-ai-provider.fly.dev/ai-provider"
  NEXT_PUBLIC_AGENT_PROVIDER_URL = "https://agent-automation-agent-provider.fly.dev/agent-provider"
  NEXT_PUBLIC_MCP_PROVIDER_URL = "https://agent-automation-mcp-provider.fly.dev/mcp-provider"
  NEXT_PUBLIC_DEBUG = "false"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "5s"
  path = "/"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[vm.restart_policy]]
  policy = "always"
