# fly.toml app configuration file generated for ai-provider-crimson-water-8145 on 2025-06-21T12:30:22+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "agent-automation-ai-provider"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  SERVER_PORT = "8080"
  SPRING_PROFILES_ACTIVE = "production"
  # Note: Set secrets using: fly secrets set HUGGINGFACE_API_KEY=your_key_here
  # HUGGINGFACE_API_KEY will be set as a secret

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "5s"
  path = "/ai-provider/actuator/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[vm.restart_policy]]
  policy = "always"
