app = "agent-automation-mcp-provider"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  SERVER_PORT = "8080"
  SPRING_PROFILES_ACTIVE = "production"
  AI_PROVIDER_BASE_URL = "https://agent-automation-ai-provider.fly.dev"
  # Supabase Remote Database - No Fly.io PostgreSQL needed
  SPRING_DATASOURCE_URL = "jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?user=postgres.srtihtbzckhristzucid&reWriteBatchedInserts=true"
  SPRING_DATASOURCE_USERNAME = "postgres.srtihtbzckhristzucid"
  # Mail Configuration - Set as secrets via flyctl
  MAIL_HOST = "smtp.gmail.com"
  MAIL_PORT = "587"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "5s"
  path = "/mcp-provider/actuator/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[vm.restart_policy]]
  policy = "always"
